version: 0.2
os: linux
files:
  - source: /index.html
    destination: /var/www/html
phases:
  install:
    commands:
      - sudo yum update -y
      - sudo yum install httpd -y
      - sudo service httpd start
      - sudo chkconfig httpd on

  
  
    